title: Greg Lukens
description: Bookmark this to keep an eye on my project updates!
url: "https://greglukens.github.io"
baseurl: ""   # keep empty for user/organization site
author:
  name: Greg Lukens
  email: your.email@university.edu

# Built-in Pages-safe plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections (optional later)
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Navigation (we'll define labels in _data/navigation.yml)
nav: true

# Markdown / code / math
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  hard_wrap: false

theme: jekyll-theme-minimal

# Social preview (optional)
logo: /assets/img/headshot.jpg

# Exclude dev files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
