title: Greg Lukens
description: Bookmark this to keep an eye on my project updates!
url: "https://greglukens.github.io"
baseurl: ""
theme: jekyll-theme-minimal
sass:
  style: compressed
author:
  name: Greg Lukens
  email: gql5196@psu.edu

# Built-in Pages-safe plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation (we'll define labels in _data/navigation.yml)
nav: true

# Markdown / code / math
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  hard_wrap: false


# Social preview (optional)
logo: /assets/img/headshot.jpg

# Exclude dev files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
